# Generated by Django 4.0.5 on 2022-07-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_cginterviews_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
