# Generated by Django 4.0.5 on 2022-07-08 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_groups_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='member',
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='groups_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
