# Generated by Django 4.0.5 on 2022-07-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_caregivermprofile_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverprofile',
            old_name='price',
            new_name='priceperhour',
        ),
    ]
