# Generated by Django 4.0.5 on 2022-06-29 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_messages_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_sent',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
