# Generated by Django 4.0.5 on 2022-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_messages_api', '0002_message_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
